[workspace]
resolver = "2"

members = [
    "crates/novn-script",
    "crates/novn",
    "crates/novn-macros",
    "crates/novn-build",
    "crates/novn-cli",
    "crates/novn-live2d",
    "crates/novn-playground",
    "examples/god_is_watching",
    "examples/example_vn",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.98"
license = "MIT OR Apache-2.0"
repository = "https://github.com/notreallyuri/novn"
homepage = "https://notreallyuri.github.io/novn"
authors = ["notreallyuri"]

[workspace.dependencies]
novn-script = { path = "crates/novn-script", version = "0.1.0" }
novn = { path = "crates/novn", version = "0.1.0" }
novn-macros = { path = "crates/novn-macros", version = "0.1.0" }
novn-build = { path = "crates/novn-build", version = "0.1.0" }
raylib = "5.5.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"

[profile.dev.package.rav1d]
opt-level = 3

[profile.wasm]
inherits = "release"
opt-level = "z"
lto = true
panic = "abort"
strip = true
