use vn_engine::raylib::prelude::*;
use vn_engine::ui::{self, ButtonStyle};
use vn_engine::{DrawContext, GameContext, Screen, ScreenState, TextStyle};

use crate::journal::{Journal, achievement_name};
use crate::style;

const LINES: [&str; 5] = [
    "A story built on \"Box 14\" and the Santa Ilde reports",
    "Made with VN_Rust",
    "Fonts: Noto Sans, Noto Serif (SIL OFL). Art generated by tools/generate_art.py",
    "Music: Emma_MA, Tozan, Centurion_of_war, Independent.nu, Bobjt (CC0)",
    "Sounds: Kenney, RPG Audio (CC0). See assets/AUDIO_CREDITS.md",
];

pub struct CreditsScreen {
    heading: TextStyle,
    body: TextStyle,
    section: TextStyle,
    achievement: TextStyle,
    back: ButtonStyle,
}

impl CreditsScreen {
    pub fn new() -> Self {
        Self {
            heading: style::heading(52.0),
            body: style::body(22.0),
            section: style::label(16.0).color(style::PARCHMENT),
            achievement: style::label(19.0).color(style::TEXT),
            back: style::button(ButtonStyle::default().size(220.0, 48.0)),
        }
    }

    fn back_rect(&self, screen: Vector2) -> Rectangle {
        Rectangle::new(
            (screen.x - self.back.width) / 2.0,
            screen.y - self.back.height - 48.0,
            self.back.width,
            self.back.height,
        )
    }
}

impl Screen for CreditsScreen {
    fn update(&mut self, mut ctx: GameContext) -> Option<ScreenState> {
        ui::load_background(&mut ctx, Some(&style::background(style::TITLE_BACKGROUND)));
        let back = self.back_rect(ui::screen_size(ctx.rl));
        let key = [KeyboardKey::KEY_ESCAPE, KeyboardKey::KEY_BACKSPACE]
            .into_iter()
            .any(|key| ctx.rl.is_key_pressed(key));

        (ui::button_clicked(&mut ctx, back, &self.back) || key).then_some(ScreenState::MainMenu)
    }

    fn draw(&self, d: &mut RaylibDrawHandle, ctx: &DrawContext) {
        let screen = ui::screen_size(d);
        let fonts = ctx.fonts();

        ui::draw_background(
            d,
            ctx.resources,
            Some(&style::background(style::TITLE_BACKGROUND)),
        );
        d.draw_rectangle(0, 0, screen.x as i32, screen.y as i32, style::BACKDROP);

        ui::draw_text_centered(
            d,
            fonts,
            "God Is Watching",
            Vector2::new(screen.x / 2.0, screen.y * 0.16),
            &self.heading,
        );

        let mut y = screen.y * 0.28;
        for line in LINES {
            ui::draw_text_centered(d, fonts, line, Vector2::new(screen.x / 2.0, y), &self.body);
            y += 36.0;
        }

        let ending = ctx
            .story
            .variable("ending")
            .map(ToString::to_string)
            .filter(|ending| ending != "none");
        y += 30.0;
        if let Some(ending) = ending {
            ui::draw_text_centered(
                d,
                fonts,
                &format!("ENDING REACHED: {}", ending.to_uppercase()),
                Vector2::new(screen.x / 2.0, y),
                &self.section,
            );
            y += 40.0;
        }

        let journal = ctx.state.get::<Journal>();
        let achievements: Vec<&str> = journal.achievements().map(achievement_name).collect();
        if !achievements.is_empty() {
            ui::draw_text_centered(
                d,
                fonts,
                "ACHIEVEMENTS",
                Vector2::new(screen.x / 2.0, y),
                &self.section,
            );
            y += 32.0;
            for achievement in achievements {
                ui::draw_text_centered(
                    d,
                    fonts,
                    achievement,
                    Vector2::new(screen.x / 2.0, y),
                    &self.achievement,
                );
                y += 28.0;
            }
        }

        ui::draw_button(d, ctx, self.back_rect(screen), "Back", &self.back);
    }
}
