[package]
name = "example_vn"
version.workspace = true
edition.workspace = true
publish = false

[features]
default = []
live2d = ["dep:novn-live2d", "novn-live2d/engine"]

[dependencies]
novn.workspace = true
serde.workspace = true
novn-live2d = { path = "../../crates/novn-live2d", optional = true }

[build-dependencies]
novn-build.workspace = true
